server:
  port: 6001

#服务的名称
spring:
  application:
    name: zuulClient

#指定注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:30001/eureka/,http://localhosttwo:30002/eureka/

#自定义路由映射
zuul:
  routes:
    apiFirst: /apigateway/apifirst/**
    apiSecond: /apigateway/apiSecond/**
  #统一入口为上面的配置，其他入口忽略
  #ignored-patterns: /*-service/**
  #忽略整个服务，对外提供接口
  #ignored-services: order-service